// generated by cdk8s
import { ApiObject, ApiObjectMetadata } from "cdk8s";
import { Construct } from "constructs";
import { KubePersistentVolumeClaimProps } from "../k8s";

/**
 *
 *
 * @schema RedisFailover
 */
export class RedisFailover extends ApiObject {
	/**
	 * Defines a "RedisFailover" API object
	 * @param scope the scope in which to define this object
	 * @param name a scope-local name for the object
	 * @param options configuration options
	 */
	public constructor(
		scope: Construct,
		name: string,
		options: RedisFailoverOptions = {}
	) {
		super(scope, name, {
			...options,
			kind: "RedisFailover",
			apiVersion: "databases.spotahome.com/v1",
		});
	}
}

/**
 * @schema RedisFailover
 */
export interface RedisFailoverOptions {
	metadata?: ApiObjectMetadata;
	spec?: {
		sentinel?: {
			replicas: number;

			resources?: RedisFailoverResources;
		};
		redis?: {
			replicas: number;
			storage?: {
				keepAfterDeletion?: boolean;

				persistentVolumeClaim?: KubePersistentVolumeClaimProps;
			};
		};
	};
}

export interface RedisFailoverResources {
	resources?: any;
	limits?: any;
}
