kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: redisfailovers.databases.spotahome.com
spec:
  group: databases.spotahome.com
  names:
    plural: redisfailovers
    singular: redisfailover
    kind: RedisFailover
    listKind: RedisFailoverList
    categories:
      - all
      - kooper
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
  conversion:
    strategy: None
  preserveUnknownFields: true
