version: "3.7"

services:
  backend:
    image: backend:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: backend

  frontend:
    image: frontend:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: frontend
        EXPOSED_PORT: 3000

  fsm:
    image: fsm:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: fsm

  gsi-receiver:
    image: gsi-receiver:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: gsi-receiver

  15kmmr:
    image: 15kmmr:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: 15kmmr
