version: "3.7"

services:
  base:
    image: docker.pkg.github.com/fortify-labs/fortify/base:${BASE_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Base.Dockerfile

  backend:
    image: docker.pkg.github.com/fortify-labs/fortify/backend:${BACKEND_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: backend
        EXPOSED_PORT: 8080

  frontend:
    image: docker.pkg.github.com/fortify-labs/fortify/frontend:${FRONTEND_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: frontend
        EXPOSED_PORT: 3000

  fsm:
    image: docker.pkg.github.com/fortify-labs/fortify/fsm:${FSM_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: fsm

  gsi-receiver:
    image: docker.pkg.github.com/fortify-labs/fortify/gsi-receiver:${GSI_RECEIVER_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: gsi-receiver
        EXPOSED_PORT: 8080

  17kmmrbot:
    image: docker.pkg.github.com/fortify-labs/fortify/17kmmrbot:${TWITCHBOT_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: 17kmmrbot

  jobs:
    image: docker.pkg.github.com/fortify-labs/fortify/jobs:${JOBS_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: jobs

  historization:
    image: docker.pkg.github.com/fortify-labs/fortify/historization:${HISTORIZATION_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: historization
