version: "3.7"
services:
  backend:
    image: backend
    build: ./services/backend

  frontend:
    image: frontend
    build: ./services/frontend
  
  fsm:
    image: fsm
    build: ./services/fsm

  gsiingress:
    image: gsiingress
    build: ./services/gsi-receiver
