version: "3.7"

services:
  backend:
    image: registry.gitlab.com/thomask33/fortify/backend:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: backend

  frontend:
    image: registry.gitlab.com/thomask33/fortify/frontend:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: frontend
        EXPOSED_PORT: 3000

  fsm:
    image: registry.gitlab.com/thomask33/fortify/fsm:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: fsm

  gsi-receiver:
    image: registry.gitlab.com/thomask33/fortify/gsi-receiver:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: gsi-receiver

  17kmmrbot:
    image: registry.gitlab.com/thomask33/fortify/17kmmrbot:${VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        SERVICE_NAME: 17kmmrbot
