version: "3.7"

services:
  base:
    image: ghcr.io/fortify-labs/fortify/base:${BASE_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Base.Dockerfile

  backend:
    image: ghcr.io/fortify-labs/fortify/backend:${BACKEND_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: backend
        EXPOSED_PORT: 8080

        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-invalidAuthToken}
        SENTRY_ORG: ${SENTRY_ORG:-invalidOrg}

  frontend:
    image: ghcr.io/fortify-labs/fortify/frontend:${FRONTEND_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./services/frontend/Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: frontend
        EXPOSED_PORT: 3000

  fsm:
    image: ghcr.io/fortify-labs/fortify/fsm:${FSM_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: fsm

        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-invalidAuthToken}
        SENTRY_ORG: ${SENTRY_ORG:-invalidOrg}

  gsi-receiver:
    image: ghcr.io/fortify-labs/fortify/gsi-receiver:${GSI_RECEIVER_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: gsi-receiver
        EXPOSED_PORT: 8080

        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-invalidAuthToken}
        SENTRY_ORG: ${SENTRY_ORG:-invalidOrg}

  17kmmrbot:
    image: ghcr.io/fortify-labs/fortify/17kmmrbot:${TWITCHBOT_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: 17kmmrbot

        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-invalidAuthToken}
        SENTRY_ORG: ${SENTRY_ORG:-invalidOrg}

  jobs:
    image: ghcr.io/fortify-labs/fortify/jobs:${JOBS_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: jobs

        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-invalidAuthToken}
        SENTRY_ORG: ${SENTRY_ORG:-invalidOrg}

  historization:
    image: ghcr.io/fortify-labs/fortify/historization:${HISTORIZATION_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: historization

        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-invalidAuthToken}
        SENTRY_ORG: ${SENTRY_ORG:-invalidOrg}
