version: "3.7"
services:
  backend:
    image: backend
    build: ./services/backend

  frontend:
    image: frontend
    build: ./services/frontend

  gsiingress:
    image: gsiingress
    build: ./services/gsi-receiver
