version: "3.7"

services:
  base:
    image: registry.gitlab.com/thomask33/fortify/base:${BASE_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Base.Dockerfile

  backend:
    image: registry.gitlab.com/thomask33/fortify/backend:${BACKEND_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: backend
        EXPOSED_PORT: 8080

  frontend:
    image: registry.gitlab.com/thomask33/fortify/frontend:${FRONTEND_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: frontend
        EXPOSED_PORT: 3000

        NEXT_PUBLIC_GRAPHQL_URI: ${NEXT_PUBLIC_GRAPHQL_URI}
        NEXT_PUBLIC_GRAPHQL_WS_URI: ${NEXT_PUBLIC_GRAPHQL_WS_URI}
        NEXT_PUBLIC_LOGIN_URL: ${NEXT_PUBLIC_LOGIN_URL}
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}

  fsm:
    image: registry.gitlab.com/thomask33/fortify/fsm:${FSM_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: fsm

  gsi-receiver:
    image: registry.gitlab.com/thomask33/fortify/gsi-receiver:${GSI_RECEIVER_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/NodeExposed.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: gsi-receiver
        EXPOSED_PORT: 8080

  17kmmrbot:
    image: registry.gitlab.com/thomask33/fortify/17kmmrbot:${TWITCHBOT_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: 17kmmrbot

  jobs:
    image: registry.gitlab.com/thomask33/fortify/jobs:${JOBS_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: jobs

  historization:
    image: registry.gitlab.com/thomask33/fortify/historization:${HISTORIZATION_VERSION:-invalidVersion}
    build:
      context: ./
      dockerfile: ./devops/docker/Node.Dockerfile

      args:
        BASE_VERSION: ${BASE_VERSION:-invalidVersion}
        SERVICE_NAME: historization
