version: "3.7"
services:
  postgres:
    image: "postgres:11"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "PG_USER"
      POSTGRES_PASSWORD: "PG_PASS"
      POSTGRES_DB: "fortify"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.13/data
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - kafka-data:/kafka
    restart: unless-stopped

  akhq:
    image: tchiotludo/akhq:latest
    environment:
      AKHQ_CONFIGURATION: >
        akhq:
          connections:
            kafka-cluster-kafka-bootstrap:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8082:8080
    restart: unless-stopped

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  redis-data:
  kafka-data:
  zookeeper-data:
  postgres-data:
