configuration: |
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access

secrets: |
  akhq:
    connections:
      kafka-cluster-kafka-bootstrap:
        properties:
          bootstrap.servers: "fortify-kafka-bootstrap:9092"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
