version: "3"

services:
  discord-webhook:
    image: ghcr.io/fortify-labs/fortify/sentry-discord-webhook:1.1.3
    build: .

    ports:
      - 8080:8080

    environment:
      LISTEN_ADDRESS: ${LISTEN_ADDRESS}
      DISCORD_WEBHOOKS: ${DISCORD_WEBHOOKS}
      SENTRY_CLIENT_SECRET: ${SENTRY_CLIENT_SECRET}
      DISABLE_STARTUP_MESSAGE: "true"
