// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * 
 *
 * @schema Middleware
 */
export class Middleware extends ApiObject {
  /**
   * Defines a "Middleware" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: MiddlewareOptions = {}) {
    super(scope, name, {
      ...options,
      kind: 'Middleware',
      apiVersion: 'traefik.containo.us/v1alpha1',
    });
  }
}

/**
 * @schema Middleware
 */
export interface MiddlewareOptions {
}

