// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * 
 *
 * @schema QuotaSpec
 */
export class QuotaSpec extends ApiObject {
  /**
   * Defines a "QuotaSpec" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: QuotaSpecOptions = {}) {
    super(scope, name, {
      ...options,
      kind: 'QuotaSpec',
      apiVersion: 'config.istio.io/v1alpha2',
    });
  }
}

/**
 * @schema QuotaSpec
 */
export interface QuotaSpecOptions {
  /**
   * Determines the quotas used for individual requests.
   *
   * @schema QuotaSpec#spec
   */
  readonly spec?: QuotaSpecSpec;

}

/**
 * Determines the quotas used for individual requests.
 *
 * @schema QuotaSpecSpec
 */
export interface QuotaSpecSpec {
  /**
   * A list of Quota rules.
   *
   * @schema QuotaSpecSpec#rules
   */
  readonly rules?: QuotaSpecSpecRules[];

}

/**
 * @schema QuotaSpecSpecRules
 */
export interface QuotaSpecSpecRules {
  /**
   * If empty, match all request.
   *
   * @schema QuotaSpecSpecRules#match
   */
  readonly match?: QuotaSpecSpecRulesMatch[];

  /**
   * The list of quotas to charge.
   *
   * @schema QuotaSpecSpecRules#quotas
   */
  readonly quotas?: QuotaSpecSpecRulesQuotas[];

}

/**
 * @schema QuotaSpecSpecRulesMatch
 */
export interface QuotaSpecSpecRulesMatch {
  /**
   * Map of attribute names to StringMatch type.
   *
   * @schema QuotaSpecSpecRulesMatch#clause
   */
  readonly clause?: { [key: string]: QuotaSpecSpecRulesMatchClause };

}

/**
 * @schema QuotaSpecSpecRulesQuotas
 */
export interface QuotaSpecSpecRulesQuotas {
  /**
   * @schema QuotaSpecSpecRulesQuotas#charge
   */
  readonly charge?: number;

  /**
   * @schema QuotaSpecSpecRulesQuotas#quota
   */
  readonly quota?: string;

}

/**
 * @schema QuotaSpecSpecRulesMatchClause
 */
export interface QuotaSpecSpecRulesMatchClause {
  /**
   * @schema QuotaSpecSpecRulesMatchClause#exact
   */
  readonly exact?: string;

  /**
   * @schema QuotaSpecSpecRulesMatchClause#prefix
   */
  readonly prefix?: string;

  /**
   * RE2 style regex-based match (https://github.com/google/re2/wiki/Syntax).
   *
   * @schema QuotaSpecSpecRulesMatchClause#regex
   */
  readonly regex?: string;

}

