// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * 
 *
 * @schema template
 */
export class template extends ApiObject {
  /**
   * Defines a "template" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: templateOptions = {}) {
    super(scope, name, {
      ...options,
      kind: 'template',
      apiVersion: 'config.istio.io/v1alpha2',
    });
  }
}

/**
 * @schema template
 */
export interface templateOptions {
  /**
   * @schema template#spec
   */
  readonly spec?: any;

}

