name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-20.04
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Alpha Release
        uses: cla-assistant/github-action@v2.0.1-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-cla-document: "https://github.com/Fortify-Labs/Fortify/blob/master/CLA.md"
          # branch should not be protected
          branch: "develop"
          allowlist: ThomasK33,dependabot*
